# Generated by Django 3.2.4 on 2021-09-09 23:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import practicas_tesisApp.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practicas_tesisApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('dni', models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El tamaño tiene que ser de 8 digitos', regex='^\\d{8}$')])),
                ('sexo', models.CharField(choices=[['Femenino', 'Femenino'], ['Masculino', 'Masculino']], max_length=10)),
                ('imagen', models.ImageField(upload_to='alumnos')),
                ('direccion', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[['Estudiante', 'Estudiante'], ['Practicante', 'Practicante'], ['Tesis', 'Tesis']], default='Estudiante', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[['Practica', 'Practica'], ['Tesis', 'Tesis']], default='', max_length=30)),
                ('estado', models.CharField(choices=[['Disponible', 'Disponible'], ['Ocupado', 'Ocupado']], default='Disponible', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('dni', models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El tamaño tiene que ser de 8 digitos', regex='^\\d{8}$')])),
                ('sexo', models.CharField(choices=[['Femenino', 'Femenino'], ['Masculino', 'Masculino']], max_length=10)),
                ('imagen', models.ImageField(upload_to='docentes')),
                ('direccion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InscripcionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.FileField(default=None, upload_to='vouchers_inscripcion_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('fut_inscripcion_tesis', models.FileField(default=None, upload_to='futs_inscripcion_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('ejemplar_tesis', models.FileField(default=None, upload_to='ejemplares_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('enviar', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aprobado', 'Aprobado'], ['Observada', 'Observada'], ['Desaprobado', 'Desaprobado']], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(default='Sin observacion', null=True)),
                ('asesor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.asesor')),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[['Disponible', 'Disponible'], ['Ocupado', 'Ocupado']], default='Disponible', max_length=30)),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(default=None, upload_to='solicitudes_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('enviar', models.BooleanField(default=False)),
                ('observacion', models.TextField(default='Sin observacion', null=True)),
                ('estado', models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aceptada', 'Aceptada'], ['Observada', 'Observada'], ['Rechazada', 'Rechazada']], default='Pendiente', max_length=30)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='SustentacionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.FileField(default=None, upload_to='vouchers_sustentacion_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('fut_sustentacion_tesis', models.FileField(default=None, upload_to='futs_sustentacion_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('resumen_tesis', models.FileField(default=None, upload_to='resumenes_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('enlace', models.CharField(max_length=50, null=True)),
                ('fecha_sustentacion', models.DateField(null=True)),
                ('enviar', models.BooleanField(default=False)),
                ('asignada', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aprobado', 'Aprobado'], ['Observada', 'Observada'], ['Desaprobado', 'Desaprobado']], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(default='Sin observacion', null=True)),
                ('inscripcionTesis', models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.inscripciontesis')),
            ],
        ),
        migrations.RemoveField(
            model_name='escuela',
            name='estado',
        ),
        migrations.CreateModel(
            name='TramiteInicioPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.FileField(default=None, upload_to='vouchers_inicio_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('carta_aceptacion', models.FileField(default=None, upload_to='aceptaciones/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('fut_inicio_practicas', models.FileField(default=None, upload_to='futs_inicio_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('plan_practicas', models.FileField(default=None, upload_to='planes_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('fecha_aceptacion', models.DateField(null=True)),
                ('enviar', models.BooleanField(default=False)),
                ('nota', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('estado', models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aprobado', 'Aprobado'], ['Observada', 'Observada'], ['Desaprobado', 'Desaprobado']], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(default='Sin observacion', null=True)),
                ('asesor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.asesor')),
                ('solicitud', models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.solicitud')),
            ],
        ),
        migrations.CreateModel(
            name='TramiteFinPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.FileField(default=None, upload_to='vouchers_final_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('informe_final_practicas', models.FileField(default=None, upload_to='informes_final_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('fut_fin_practicas', models.FileField(default=None, upload_to='futs_fin_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('certificado_practicas', models.FileField(default=None, upload_to='certificados_practicas/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('nota', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('estado', models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aprobado', 'Aprobado'], ['Observada', 'Observada'], ['Desaprobado', 'Desaprobado']], default='Pendiente', max_length=30)),
                ('observacion', models.TextField(default='Sin observacion', null=True)),
                ('enviar', models.BooleanField(default=False)),
                ('tramiteInicioPractica', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.tramiteiniciopractica')),
            ],
        ),
        migrations.CreateModel(
            name='TesisJurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('jurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas_tesisApp.jurado')),
                ('sustentacionTesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practicas_tesisApp.sustentaciontesis')),
            ],
        ),
        migrations.AddField(
            model_name='sustentaciontesis',
            name='jurados',
            field=models.ManyToManyField(default='', through='practicas_tesisApp.TesisJurado', to='practicas_tesisApp.Jurado'),
        ),
        migrations.CreateModel(
            name='SolicitudTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(default=None, upload_to='solicitudes_tesis/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('enviar', models.BooleanField(default=False)),
                ('observacion', models.TextField(default='Sin observacion', null=True)),
                ('estado', models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aceptada', 'Aceptada'], ['Observada', 'Observada'], ['Rechazada', 'Rechazada']], default='Pendiente', max_length=30)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('dni', models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El tamaño tiene que ser de 8 digitos', regex='^\\d{8}$')])),
                ('sexo', models.CharField(choices=[['Femenino', 'Femenino'], ['Masculino', 'Masculino']], max_length=10)),
                ('imagen', models.ImageField(upload_to='secretarias')),
                ('direccion', models.CharField(max_length=30)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.escuela')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inscripciontesis',
            name='solicitud',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.solicitudtesis'),
        ),
        migrations.AddField(
            model_name='docente',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.escuela'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('dni', models.CharField(default='', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='El tamaño tiene que ser de 8 digitos', regex='^\\d{8}$')])),
                ('sexo', models.CharField(choices=[['Femenino', 'Femenino'], ['Masculino', 'Masculino']], max_length=10)),
                ('imagen', models.ImageField(upload_to='secretarias')),
                ('direccion', models.CharField(max_length=30)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.escuela')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asesor',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.docente'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.escuela'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActaAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_aprobacion', models.FileField(default=None, upload_to='actas_aprobacion/%Y/%m/%d/', validators=[practicas_tesisApp.validators.validate_file_extension])),
                ('horas', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(600)])),
                ('terminado', models.BooleanField(default=False)),
                ('asesor', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.asesor')),
                ('tramiteFinPractica', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='practicas_tesisApp.tramitefinpractica')),
            ],
        ),
        migrations.AddConstraint(
            model_name='asesor',
            constraint=models.UniqueConstraint(fields=('tipo', 'docente'), name='Tipo Asesor ya asignado'),
        ),
    ]
