# Generated by Django 3.2.4 on 2021-09-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicas_tesisApp', '0002_auto_20210909_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustentaciontesis',
            name='estado',
        ),
    ]
