# Generated by Django 3.2.4 on 2021-09-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas_tesisApp', '0003_remove_sustentaciontesis_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustentaciontesis',
            name='estado',
            field=models.CharField(choices=[['Pendiente', 'Pendiente'], ['Aprobado', 'Aprobado'], ['Observada', 'Observada'], ['Desaprobado', 'Desaprobado']], default='Pendiente', max_length=30),
        ),
    ]
