# Generated by Django 3.2.4 on 2021-09-11 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas_tesisApp', '0005_auto_20210911_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustentaciontesis',
            name='nota',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
