# Generated by Django 3.2.4 on 2021-09-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicas_tesisApp', '0007_auto_20210914_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramitefinpractica',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='tramiteiniciopractica',
            name='nota',
        ),
    ]
