# Generated by Django 3.2.4 on 2021-09-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridadApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
